spring.application.name=mosip-uin-deletion

# Database 1: Basic Details Database (defaultdb)
spring.datasource.basic.jdbc-url=jdbc:postgresql://basicdetails-mosip-uindeletion123.i.aivencloud.com:20760/defaultdb?sslmode=require
spring.datasource.basic.username=avnadmin
spring.datasource.basic.password=AVNS_FFoMkhXWnM1cbEEb-EM
spring.datasource.basic.driver-class-name=org.postgresql.Driver

# Database 2: Hashed UIN Database (uin-hashing)
spring.datasource.hashing.jdbc-url=jdbc:postgresql://uin-hashing-harshbontala188-df34.j.aivencloud.com:24845/defaultdb?sslmode=require
spring.datasource.hashing.username=avnadmin
spring.datasource.hashing.password=AVNS_C9vZjT7iTvBt1znplr4
spring.datasource.hashing.driver-class-name=org.postgresql.Driver

# JPA Common Settings
spring.jpa.open-in-view=true
